refactor(manage): run frontend

diff --git a/manage b/manage
--- a/manage
+++ b/manage
@@ -9,6 +9,9 @@ function print_help {
 
 cmd=$1
 apps=("account" "announcement" "conf" "contest" "options" "problem" "submission")
+backend="http://127.0.0.1:7890"
+backend_cmd="python3 manage.py runserver"
+frontend_cmd="node build/dev-server.js"
 
 function clean {
   rm -rf ./data/zips
@@ -33,59 +36,90 @@ function run_onl {
   # using postgres
   # docker run -it -d -e POSTGRES_DB=onlinejudge -e POSTGRES_USER=onlinejudge -e POSTGRES_PASSWORD=onlinejudge -p 5435:5432 --name oj-postgres-dev postgres:10-alpine
   
+  if ! command which python3 | grep venv > /dev/null; then
+    source venv/bin/activate
+  fi
+  
   # run dramatiq
-  pgrep dramatiq > /dev/null
-  if [[ $? -ne 0 ]]; then
+  if ! command pgrep dramatiq > /dev/null; then
     echo "running dramatiq ..."
     python3 manage.py rundramatiq &>data/log/dramatiq.log &
+    [[ $? -ne 0 ]] && echo "Error: fail to run dramatiq"
   else
-    echo "dramatiq is already running ..."
+    echo "dramatiq is already running"
   fi
 
   # run redis
-  docker container ls | grep redis > /dev/null
-  if [[ $? -ne 0 ]]; then
+  if ! command docker container ls | grep redis > /dev/null; then
     echo "running redis in docker ..."
-    docker ps -a | grep redis > /dev/null
-    if [[ $? -ne 0 ]]; then
+    if ! command docker ps -a | grep redis > /dev/null; then
       docker run -it -d -p 6380:6379 --name oj-redis-dev redis:4.0-alpine > /dev/null
     else
       container_id=$(docker ps -a | grep redis | awk '{print $1}')
       docker container start $container_id
     fi
+    [[ $? -ne 0 ]] && echo "Error: fail to run redis docker"
   else
     echo "redis is already running"
   fi
 
   # run onl
-  pgrep -f "python3 manage.py runserver" > /dev/null
-  if [[ $? -ne 0 ]]; then
-    echo "running onl ..."
+  if ! command pgrep -f "$backend_cmd" > /dev/null; then
+    echo "running onl controller ..."
     python3 manage.py runserver 0.0.0.0:7890 &>data/log/onl.log &
+    [[ $? -ne 0 ]] && echo "Error: fail to run onl controll"
   else
-    echo "onl is already running ..."
+    echo "onl controller is already running"
+  fi
+
+  # run frontend
+  if ! command pgrep -f "$frontend_cmd" > /dev/null; then
+    echo "running onl frontend ..."
+    if [[ -z $FRONTEND ]]; then
+      echo "environment variable FRONTEND is empty, you should run frontend yourself"
+    else
+      fe_log_path="$(pwd)/data/log/npm.log"
+      export NVM_DIR="$HOME/.nvm"
+      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
+      (cd $FRONTEND; nvm use v8.12.0; TARGET=$backend npm run dev &> $fe_log_path &)
+      [[ $? -ne 0 ]] && echo "Error: fail to run onl frontend"
+    fi
+  else
+    echo "onl frontend is already running"
   fi
 }
 
 function stop_onl {
   pkill dramatiq
-  pkill -f "python3 manage.py runserver"
+  pkill -f "$backend_cmd"
   docker container stop oj-redis-dev > /dev/null
+  pkill -f "$frontend_cmd"
 }
 
-if [[ $cmd == "make" || $cmd == "makemigrations" ]]; then
-  for app in "${apps[@]}"; do
-    python3 manage.py makemigrations $app
-  done
-elif [[ $cmd == "migrate" ]]; then
-  migrate
-elif [[ $cmd == "clean" ]]; then
-  clean
-elif [[ $cmd == "rebuild" ]]; then
-  clean
-  migrate
-elif [[ $cmd == "run" ]]; then
-  run_onl
-elif [[ $cmd == "stop" ]]; then
-  stop_onl
-fi
+case $cmd in
+  "make" | "makemigrations" )
+    for app in "${apps[@]}"; do
+      python3 manage.py makemigrations $app
+    done
+    ;;
+  "migrate" )
+    migrate
+    ;;
+  "clean" )
+    clean
+    ;;
+  "rebuild" )
+    clean
+    rebuild
+    ;;
+  "run" )
+    run_onl
+    ;;
+  "stop" )
+    stop_onl
+    ;;
+  * )
+    echo "unknown commmand: $cmd"
+    print_help
+    ;;
+esac
